CREATE TABLE Customers
(
   CustomerID INT NOT NULL IDENTITY PRIMARY KEY,
   Name VARCHAR(30),
   LastName VARCHAR(30)
);

CREATE TABLE Stores
(
   StoreName VARCHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE Orders
(
   OrderID INT NOT NULL IDENTITY PRIMARY KEY,
   CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers(CustomerID),
   StoreName VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Stores(StoreName),
   OrderedDate DATE NOT NULL,
   Total DECIMAL NOT NULL
);

CREATE TABLE Products
(
   ProductName VARCHAR(30) NOT NULL PRIMARY KEY, 
   Price DECIMAL NOT NULL,
   Description VARCHAR(30)
);

CREATE TABLE Purchases
(
   PurchasesID INT NOT NULL IDENTITY PRIMARY KEY,
   ProductName VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Products(ProductName),
   OrderID INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderID)
);

CREATE TABLE Inventory
(
   InventoryID INT NOT NULL IDENTITY PRIMARY KEY,
   ProductName VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Products(ProductName),
   StoreName VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Stores(StoreName)
);